apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-manager
  labels:
    app: secret-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: secret-manager
  template:
    metadata:
      labels:
        app: secret-manager
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: proxycontainer
        image: lachlanevenson/k8s-kubectl
        command: ["kubectl","proxy","--port=8001"]
      - name: secret-manager
        image: {{ .Values.image.registry }}:{{ .Values.image.tag }}
        env:
        - name: AWS_ACCOUNT
          value: "{{ .Values.aws.accountId }}"
        command: [ "python3", "/app/k8s-secret-from-aws-secret-mgr.py"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}