---
apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: {{ .Values.rbac.clusterRoleName }}
    rules:
      - apiGroups: ["*"]
        resources: ["namespaces","pods","secrets","secretmanagers"]
        verbs: ["get","watch","list","create"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: {{ .Values.rbac.clusterRoleName }}
    subjects:
    - kind: ServiceAccount
      name: {{ .Values.serviceAccountName }}
      namespace: secret-manager
    roleRef:
      kind: ClusterRole
      name: {{ .Values.rbac.clusterRoleName }}
      apiGroup: rbac.authorization.k8s.io
kind: List