---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretmanagers.kubernetes-client.io
spec:
  scope: Namespaced
  group: kubernetes-client.io
  version: v1
  names:
    kind: SecretManager
    singular: secretmanager
    plural: secretmanagers
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            awsSecret:
              type: string
              description: "AWS Secret Name"
            region:
              type: string
              description: "AWS region of secret"
            namespace:
              type: string
              description: "Namespace of where to create the secret"
            secretType:
              type: string
              description: "Secret type i.e docker or Opaque"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretmanager-crd
rules:
- apiGroups:
  - kubernetes-client.io
  resources:
  - secretmanager
  - secretmanager/finalizers
  verbs: [ get, list, create, update, delete, deletecollection, watch ]
