
replicaCount: 1

image:
  registry: imranawan/k8s-secret-manager-operator
  tag: v1.0.0
  pullPolicy: Always

aws:
  accountId: "<accountId>"

serviceAccountName: read-secrets

rbac:
 clusterRoleName: read-aws-secrets
 clusterBindingNamespace: <clusterBindingNamespace>