
replicaCount: 1

image:
  registry: imranawan/k8s-secret-manager-operator
  tag: v1.0.0
  pullPolicy: IfNotPresent

aws:
  accountId: "<account_id>"

serviceAccountName: "<iam_service_name>"

rbac:
 clusterRoleName: read-aws-secrets