
replicaCount: 1

image:
  registry: imranawan/k8s-secret-manager-operator
  tag: 1.0.0
  pullPolicy: Always

aws:
  accountId: "134292970725"


serviceAccountName: read-aws-secrets


rbac:
 clusterRoleName: read-aws-secrets